// AUTO-GENERATED by @agent-native/core — do not edit manually.
// Regenerated when files in actions/ change.
// This file augments the ActionRegistry interface so that useActionQuery and
// useActionMutation infer the correct types from your action definitions.

/** Extract the return type and parameter type from a defineAction module. */
type ActionEntry<T> = T extends { default: { run: (...args: infer A) => infer R } }
  ? {
      result: Awaited<R>;
      params: A extends [infer P, ...any[]] ? P : Record<string, any>;
    }
  : { result: any; params: Record<string, any> };

declare global {
  interface AgentNativeActionRegistry {
    "hello": ActionEntry<typeof import("../actions/hello")>;
    "navigate": ActionEntry<typeof import("../actions/navigate")>;
    "provider-api-request": ActionEntry<typeof import("../actions/provider-api-request")>;
    "view-screen": ActionEntry<typeof import("../actions/view-screen")>;
    "get-feature-flags": ActionEntry<typeof import("@agent-native/core/feature-flags/actions/get-feature-flags")>;
    "list-feature-flags": ActionEntry<typeof import("@agent-native/core/feature-flags/actions/list-feature-flags")>;
    "set-feature-flag": ActionEntry<typeof import("@agent-native/core/feature-flags/actions/set-feature-flag")>;
    "get-launchdarkly-flags": ActionEntry<typeof import("@agent-native/core/launchdarkly/actions/get-launchdarkly-flags")>;
    "get-labs": ActionEntry<typeof import("@agent-native/core/labs/actions/get-labs")>;
    "set-lab": ActionEntry<typeof import("@agent-native/core/labs/actions/set-lab")>;
    "get-chatgpt-subscription-status": ActionEntry<typeof import("@agent-native/core/agent/actions/get-chatgpt-subscription-status")>;
    "disconnect-chatgpt-subscription": ActionEntry<typeof import("@agent-native/core/agent/actions/disconnect-chatgpt-subscription")>;
    "preview-secret-removal": ActionEntry<typeof import("@agent-native/core/secrets/actions/preview-secret-removal")>;
    "list-api-keys": ActionEntry<typeof import("@agent-native/core/secrets/actions/list-api-keys")>;
    "delete-api-key": ActionEntry<typeof import("@agent-native/core/secrets/actions/delete-api-key")>;
    "check-provider-key": ActionEntry<typeof import("@agent-native/core/agent/actions/check-provider-key")>;
    "manage-provider-key-policy": ActionEntry<typeof import("@agent-native/core/agent/actions/manage-provider-key-policy")>;
    "manage-builder-connection": ActionEntry<typeof import("@agent-native/core/agent/actions/manage-builder-connection")>;
    "get-provider-models": ActionEntry<typeof import("@agent-native/core/agent/actions/get-provider-models")>;
    "manage-provider-models": ActionEntry<typeof import("@agent-native/core/agent/actions/manage-provider-models")>;
    "list-model-providers": ActionEntry<typeof import("@agent-native/core/agent/actions/list-model-providers")>;
    "get-hosted-harness-config": ActionEntry<typeof import("@agent-native/core/hosted-harness/actions/get-hosted-harness-config")>;
    "set-hosted-harness-enabled": ActionEntry<typeof import("@agent-native/core/hosted-harness/actions/set-hosted-harness-enabled")>;
    "set-tool-approval-policy": ActionEntry<typeof import("@agent-native/core/agent/actions/set-tool-approval-policy")>;
    "share-resource": ActionEntry<typeof import("@agent-native/core/sharing/actions/share-resource")>;
    "unshare-resource": ActionEntry<typeof import("@agent-native/core/sharing/actions/unshare-resource")>;
    "list-resource-shares": ActionEntry<typeof import("@agent-native/core/sharing/actions/list-resource-shares")>;
    "set-resource-visibility": ActionEntry<typeof import("@agent-native/core/sharing/actions/set-resource-visibility")>;
    "upload-image": ActionEntry<typeof import("@agent-native/core/file-upload/actions/upload-image")>;
    "get-file-storage": ActionEntry<typeof import("@agent-native/core/file-upload/actions/get-file-storage")>;
    "manage-file-storage": ActionEntry<typeof import("@agent-native/core/file-upload/actions/manage-file-storage")>;
    "manage-service-providers": ActionEntry<typeof import("@agent-native/core/agent/actions/manage-service-providers")>;
    "get-infrastructure-status": ActionEntry<typeof import("@agent-native/core/agent/actions/get-infrastructure-status")>;
    "list-messaging-channels": ActionEntry<typeof import("@agent-native/core/integrations/actions/list-messaging-channels")>;
    "manage-messaging-channel": ActionEntry<typeof import("@agent-native/core/integrations/actions/manage-messaging-channel")>;
    "list-workspace-user-groups": ActionEntry<typeof import("@agent-native/core/workspace-connections/actions/list-workspace-user-groups")>;
    "upsert-workspace-user-group": ActionEntry<typeof import("@agent-native/core/workspace-connections/actions/upsert-workspace-user-group")>;
    "bulk-update-workspace-user-groups": ActionEntry<typeof import("@agent-native/core/workspace-connections/actions/bulk-update-workspace-user-groups")>;
    "delete-workspace-user-group": ActionEntry<typeof import("@agent-native/core/workspace-connections/actions/delete-workspace-user-group")>;
    "context-manifest-get": ActionEntry<typeof import("@agent-native/core/agent/context-xray/actions/context-manifest-get")>;
    "context-pin": ActionEntry<typeof import("@agent-native/core/agent/context-xray/actions/context-pin")>;
    "context-evict": ActionEntry<typeof import("@agent-native/core/agent/context-xray/actions/context-evict")>;
    "context-restore": ActionEntry<typeof import("@agent-native/core/agent/context-xray/actions/context-restore")>;
    "context-report": ActionEntry<typeof import("@agent-native/core/agent/context-xray/actions/context-report")>;
    "get-localization-preference": ActionEntry<typeof import("@agent-native/core/localization/actions/get-localization-preference")>;
    "set-localization-preference": ActionEntry<typeof import("@agent-native/core/localization/actions/set-localization-preference")>;
    "get-usage-alerts": ActionEntry<typeof import("@agent-native/core/usage/actions/get-usage-alerts")>;
    "manage-usage-alert": ActionEntry<typeof import("@agent-native/core/usage/actions/manage-usage-alert")>;
    "get-usage-metrics": ActionEntry<typeof import("@agent-native/core/usage/actions/get-usage-metrics")>;
    "get-builder-credit-usage": ActionEntry<typeof import("@agent-native/core/usage/actions/get-builder-credit-usage")>;
    "get-builder-credit-status": ActionEntry<typeof import("@agent-native/core/usage/actions/get-builder-credit-status")>;
    "get-builder-referral-info": ActionEntry<typeof import("@agent-native/core/usage/actions/get-builder-referral-info")>;
    "create-resource-version": ActionEntry<typeof import("@agent-native/core/history/actions/create-resource-version")>;
    "list-resource-versions": ActionEntry<typeof import("@agent-native/core/history/actions/list-resource-versions")>;
    "get-resource-version": ActionEntry<typeof import("@agent-native/core/history/actions/get-resource-version")>;
    "restore-resource-version": ActionEntry<typeof import("@agent-native/core/history/actions/restore-resource-version")>;
    "list-resource-history": ActionEntry<typeof import("@agent-native/core/history/actions/list-resource-history")>;
    "list-observability-reviews": ActionEntry<typeof import("@agent-native/core/observability/actions/list-observability-reviews")>;
    "get-observability-review-app": ActionEntry<typeof import("@agent-native/core/observability/actions/get-observability-review-app")>;
    "get-observability-review-detail": ActionEntry<typeof import("@agent-native/core/observability/actions/get-observability-review-detail")>;
    "get-observability-review-summary-source": ActionEntry<typeof import("@agent-native/core/observability/actions/get-observability-review-summary-source")>;
    "save-observability-review-summary": ActionEntry<typeof import("@agent-native/core/observability/actions/save-observability-review-summary")>;
    "save-observability-review-feedback": ActionEntry<typeof import("@agent-native/core/observability/actions/save-observability-review-feedback")>;
    "save-observability-instruction-update": ActionEntry<typeof import("@agent-native/core/observability/actions/save-observability-instruction-update")>;
    "list-review-comments": ActionEntry<typeof import("@agent-native/core/review/actions/list-review-comments")>;
    "create-review-comment": ActionEntry<typeof import("@agent-native/core/review/actions/create-review-comment")>;
    "reply-review-comment": ActionEntry<typeof import("@agent-native/core/review/actions/reply-review-comment")>;
    "resolve-review-thread": ActionEntry<typeof import("@agent-native/core/review/actions/resolve-review-thread")>;
    "update-review-comment-anchor": ActionEntry<typeof import("@agent-native/core/review/actions/update-review-comment-anchor")>;
    "delete-review-comment": ActionEntry<typeof import("@agent-native/core/review/actions/delete-review-comment")>;
    "update-review-comment": ActionEntry<typeof import("@agent-native/core/review/actions/update-review-comment")>;
    "consume-review-feedback": ActionEntry<typeof import("@agent-native/core/review/actions/consume-review-feedback")>;
    "get-review-feedback": ActionEntry<typeof import("@agent-native/core/review/actions/get-review-feedback")>;
    "set-review-status": ActionEntry<typeof import("@agent-native/core/review/actions/set-review-status")>;
    "send-review-thread-to-agent": ActionEntry<typeof import("@agent-native/core/review/actions/send-review-thread-to-agent")>;
    "react-to-review-comment": ActionEntry<typeof import("@agent-native/core/review/actions/react-to-review-comment")>;
    "set-review-thread-unread": ActionEntry<typeof import("@agent-native/core/review/actions/set-review-thread-unread")>;
    "set-review-threads-unread": ActionEntry<typeof import("@agent-native/core/review/actions/set-review-threads-unread")>;
    "set-review-thread-muted": ActionEntry<typeof import("@agent-native/core/review/actions/set-review-thread-muted")>;
    "create-resource-suggestion": ActionEntry<typeof import("@agent-native/core/review/suggestions/actions/create-resource-suggestion")>;
    "create-resource-suggestion-proposal": ActionEntry<typeof import("@agent-native/core/review/suggestions/actions/create-resource-suggestion-proposal")>;
    "get-resource-suggestion-proposal-by-creation-key": ActionEntry<typeof import("@agent-native/core/review/suggestions/actions/get-resource-suggestion-proposal-by-creation-key")>;
    "decide-resource-suggestion-proposal": ActionEntry<typeof import("@agent-native/core/review/suggestions/actions/decide-resource-suggestion-proposal")>;
    "update-resource-suggestion": ActionEntry<typeof import("@agent-native/core/review/suggestions/actions/update-resource-suggestion")>;
    "list-resource-suggestions": ActionEntry<typeof import("@agent-native/core/review/suggestions/actions/list-resource-suggestions")>;
    "get-resource-suggestion": ActionEntry<typeof import("@agent-native/core/review/suggestions/actions/get-resource-suggestion")>;
    "decide-resource-suggestion": ActionEntry<typeof import("@agent-native/core/review/suggestions/actions/decide-resource-suggestion")>;
  }
}

declare module "@agent-native/core/client" {
  interface ActionRegistry extends AgentNativeActionRegistry {}
}

declare module "@agent-native/core/client/hooks" {
  interface ActionRegistry extends AgentNativeActionRegistry {}
}

export {};
