// AUTO-GENERATED by @agent-native/core — do not edit manually.
// Static-import registry of every action file. Bundlers (Nitro, Rolldown)
// see these imports and include the action modules in the server bundle.
// The agent-chat plugin normalizes each module into an ActionEntry shape.
import * as a_hello from "../actions/hello";
import * as a_navigate from "../actions/navigate";
import * as a_provider_api_request from "../actions/provider-api-request";
import * as a_view_screen from "../actions/view-screen";
import * as a_get_feature_flags from "@agent-native/core/feature-flags/actions/get-feature-flags";
import * as a_list_feature_flags from "@agent-native/core/feature-flags/actions/list-feature-flags";
import * as a_set_feature_flag from "@agent-native/core/feature-flags/actions/set-feature-flag";
import * as a_get_launchdarkly_flags from "@agent-native/core/launchdarkly/actions/get-launchdarkly-flags";
import * as a_get_labs from "@agent-native/core/labs/actions/get-labs";
import * as a_set_lab from "@agent-native/core/labs/actions/set-lab";
import * as a_get_chatgpt_subscription_status from "@agent-native/core/agent/actions/get-chatgpt-subscription-status";
import * as a_disconnect_chatgpt_subscription from "@agent-native/core/agent/actions/disconnect-chatgpt-subscription";
import * as a_preview_secret_removal from "@agent-native/core/secrets/actions/preview-secret-removal";
import * as a_list_api_keys from "@agent-native/core/secrets/actions/list-api-keys";
import * as a_delete_api_key from "@agent-native/core/secrets/actions/delete-api-key";
import * as a_check_provider_key from "@agent-native/core/agent/actions/check-provider-key";
import * as a_manage_provider_key_policy from "@agent-native/core/agent/actions/manage-provider-key-policy";
import * as a_manage_builder_connection from "@agent-native/core/agent/actions/manage-builder-connection";
import * as a_get_provider_models from "@agent-native/core/agent/actions/get-provider-models";
import * as a_manage_provider_models from "@agent-native/core/agent/actions/manage-provider-models";
import * as a_list_model_providers from "@agent-native/core/agent/actions/list-model-providers";
import * as a_get_hosted_harness_config from "@agent-native/core/hosted-harness/actions/get-hosted-harness-config";
import * as a_set_hosted_harness_enabled from "@agent-native/core/hosted-harness/actions/set-hosted-harness-enabled";
import * as a_set_tool_approval_policy from "@agent-native/core/agent/actions/set-tool-approval-policy";
import * as a_share_resource from "@agent-native/core/sharing/actions/share-resource";
import * as a_unshare_resource from "@agent-native/core/sharing/actions/unshare-resource";
import * as a_list_resource_shares from "@agent-native/core/sharing/actions/list-resource-shares";
import * as a_set_resource_visibility from "@agent-native/core/sharing/actions/set-resource-visibility";
import * as a_upload_image from "@agent-native/core/file-upload/actions/upload-image";
import * as a_get_file_storage from "@agent-native/core/file-upload/actions/get-file-storage";
import * as a_manage_file_storage from "@agent-native/core/file-upload/actions/manage-file-storage";
import * as a_manage_service_providers from "@agent-native/core/agent/actions/manage-service-providers";
import * as a_get_infrastructure_status from "@agent-native/core/agent/actions/get-infrastructure-status";
import * as a_list_messaging_channels from "@agent-native/core/integrations/actions/list-messaging-channels";
import * as a_manage_messaging_channel from "@agent-native/core/integrations/actions/manage-messaging-channel";
import * as a_list_workspace_user_groups from "@agent-native/core/workspace-connections/actions/list-workspace-user-groups";
import * as a_upsert_workspace_user_group from "@agent-native/core/workspace-connections/actions/upsert-workspace-user-group";
import * as a_bulk_update_workspace_user_groups from "@agent-native/core/workspace-connections/actions/bulk-update-workspace-user-groups";
import * as a_delete_workspace_user_group from "@agent-native/core/workspace-connections/actions/delete-workspace-user-group";
import * as a_context_manifest_get from "@agent-native/core/agent/context-xray/actions/context-manifest-get";
import * as a_context_pin from "@agent-native/core/agent/context-xray/actions/context-pin";
import * as a_context_evict from "@agent-native/core/agent/context-xray/actions/context-evict";
import * as a_context_restore from "@agent-native/core/agent/context-xray/actions/context-restore";
import * as a_context_report from "@agent-native/core/agent/context-xray/actions/context-report";
import * as a_get_localization_preference from "@agent-native/core/localization/actions/get-localization-preference";
import * as a_set_localization_preference from "@agent-native/core/localization/actions/set-localization-preference";
import * as a_get_usage_alerts from "@agent-native/core/usage/actions/get-usage-alerts";
import * as a_manage_usage_alert from "@agent-native/core/usage/actions/manage-usage-alert";
import * as a_get_usage_metrics from "@agent-native/core/usage/actions/get-usage-metrics";
import * as a_get_builder_credit_usage from "@agent-native/core/usage/actions/get-builder-credit-usage";
import * as a_get_builder_credit_status from "@agent-native/core/usage/actions/get-builder-credit-status";
import * as a_get_builder_referral_info from "@agent-native/core/usage/actions/get-builder-referral-info";
import * as a_create_resource_version from "@agent-native/core/history/actions/create-resource-version";
import * as a_list_resource_versions from "@agent-native/core/history/actions/list-resource-versions";
import * as a_get_resource_version from "@agent-native/core/history/actions/get-resource-version";
import * as a_restore_resource_version from "@agent-native/core/history/actions/restore-resource-version";
import * as a_list_resource_history from "@agent-native/core/history/actions/list-resource-history";
import * as a_list_observability_reviews from "@agent-native/core/observability/actions/list-observability-reviews";
import * as a_get_observability_review_app from "@agent-native/core/observability/actions/get-observability-review-app";
import * as a_get_observability_review_detail from "@agent-native/core/observability/actions/get-observability-review-detail";
import * as a_get_observability_review_summary_source from "@agent-native/core/observability/actions/get-observability-review-summary-source";
import * as a_save_observability_review_summary from "@agent-native/core/observability/actions/save-observability-review-summary";
import * as a_save_observability_review_feedback from "@agent-native/core/observability/actions/save-observability-review-feedback";
import * as a_save_observability_instruction_update from "@agent-native/core/observability/actions/save-observability-instruction-update";
import * as a_list_review_comments from "@agent-native/core/review/actions/list-review-comments";
import * as a_create_review_comment from "@agent-native/core/review/actions/create-review-comment";
import * as a_reply_review_comment from "@agent-native/core/review/actions/reply-review-comment";
import * as a_resolve_review_thread from "@agent-native/core/review/actions/resolve-review-thread";
import * as a_update_review_comment_anchor from "@agent-native/core/review/actions/update-review-comment-anchor";
import * as a_delete_review_comment from "@agent-native/core/review/actions/delete-review-comment";
import * as a_update_review_comment from "@agent-native/core/review/actions/update-review-comment";
import * as a_consume_review_feedback from "@agent-native/core/review/actions/consume-review-feedback";
import * as a_get_review_feedback from "@agent-native/core/review/actions/get-review-feedback";
import * as a_set_review_status from "@agent-native/core/review/actions/set-review-status";
import * as a_send_review_thread_to_agent from "@agent-native/core/review/actions/send-review-thread-to-agent";
import * as a_react_to_review_comment from "@agent-native/core/review/actions/react-to-review-comment";
import * as a_set_review_thread_unread from "@agent-native/core/review/actions/set-review-thread-unread";
import * as a_set_review_threads_unread from "@agent-native/core/review/actions/set-review-threads-unread";
import * as a_set_review_thread_muted from "@agent-native/core/review/actions/set-review-thread-muted";
import * as a_create_resource_suggestion from "@agent-native/core/review/suggestions/actions/create-resource-suggestion";
import * as a_create_resource_suggestion_proposal from "@agent-native/core/review/suggestions/actions/create-resource-suggestion-proposal";
import * as a_get_resource_suggestion_proposal_by_creation_key from "@agent-native/core/review/suggestions/actions/get-resource-suggestion-proposal-by-creation-key";
import * as a_decide_resource_suggestion_proposal from "@agent-native/core/review/suggestions/actions/decide-resource-suggestion-proposal";
import * as a_update_resource_suggestion from "@agent-native/core/review/suggestions/actions/update-resource-suggestion";
import * as a_list_resource_suggestions from "@agent-native/core/review/suggestions/actions/list-resource-suggestions";
import * as a_get_resource_suggestion from "@agent-native/core/review/suggestions/actions/get-resource-suggestion";
import * as a_decide_resource_suggestion from "@agent-native/core/review/suggestions/actions/decide-resource-suggestion";

const modules: Record<string, unknown> = {
  "hello": a_hello,
  "navigate": a_navigate,
  "provider-api-request": a_provider_api_request,
  "view-screen": a_view_screen,
  "get-feature-flags": a_get_feature_flags,
  "list-feature-flags": a_list_feature_flags,
  "set-feature-flag": a_set_feature_flag,
  "get-launchdarkly-flags": a_get_launchdarkly_flags,
  "get-labs": a_get_labs,
  "set-lab": a_set_lab,
  "get-chatgpt-subscription-status": a_get_chatgpt_subscription_status,
  "disconnect-chatgpt-subscription": a_disconnect_chatgpt_subscription,
  "preview-secret-removal": a_preview_secret_removal,
  "list-api-keys": a_list_api_keys,
  "delete-api-key": a_delete_api_key,
  "check-provider-key": a_check_provider_key,
  "manage-provider-key-policy": a_manage_provider_key_policy,
  "manage-builder-connection": a_manage_builder_connection,
  "get-provider-models": a_get_provider_models,
  "manage-provider-models": a_manage_provider_models,
  "list-model-providers": a_list_model_providers,
  "get-hosted-harness-config": a_get_hosted_harness_config,
  "set-hosted-harness-enabled": a_set_hosted_harness_enabled,
  "set-tool-approval-policy": a_set_tool_approval_policy,
  "share-resource": a_share_resource,
  "unshare-resource": a_unshare_resource,
  "list-resource-shares": a_list_resource_shares,
  "set-resource-visibility": a_set_resource_visibility,
  "upload-image": a_upload_image,
  "get-file-storage": a_get_file_storage,
  "manage-file-storage": a_manage_file_storage,
  "manage-service-providers": a_manage_service_providers,
  "get-infrastructure-status": a_get_infrastructure_status,
  "list-messaging-channels": a_list_messaging_channels,
  "manage-messaging-channel": a_manage_messaging_channel,
  "list-workspace-user-groups": a_list_workspace_user_groups,
  "upsert-workspace-user-group": a_upsert_workspace_user_group,
  "bulk-update-workspace-user-groups": a_bulk_update_workspace_user_groups,
  "delete-workspace-user-group": a_delete_workspace_user_group,
  "context-manifest-get": a_context_manifest_get,
  "context-pin": a_context_pin,
  "context-evict": a_context_evict,
  "context-restore": a_context_restore,
  "context-report": a_context_report,
  "get-localization-preference": a_get_localization_preference,
  "set-localization-preference": a_set_localization_preference,
  "get-usage-alerts": a_get_usage_alerts,
  "manage-usage-alert": a_manage_usage_alert,
  "get-usage-metrics": a_get_usage_metrics,
  "get-builder-credit-usage": a_get_builder_credit_usage,
  "get-builder-credit-status": a_get_builder_credit_status,
  "get-builder-referral-info": a_get_builder_referral_info,
  "create-resource-version": a_create_resource_version,
  "list-resource-versions": a_list_resource_versions,
  "get-resource-version": a_get_resource_version,
  "restore-resource-version": a_restore_resource_version,
  "list-resource-history": a_list_resource_history,
  "list-observability-reviews": a_list_observability_reviews,
  "get-observability-review-app": a_get_observability_review_app,
  "get-observability-review-detail": a_get_observability_review_detail,
  "get-observability-review-summary-source": a_get_observability_review_summary_source,
  "save-observability-review-summary": a_save_observability_review_summary,
  "save-observability-review-feedback": a_save_observability_review_feedback,
  "save-observability-instruction-update": a_save_observability_instruction_update,
  "list-review-comments": a_list_review_comments,
  "create-review-comment": a_create_review_comment,
  "reply-review-comment": a_reply_review_comment,
  "resolve-review-thread": a_resolve_review_thread,
  "update-review-comment-anchor": a_update_review_comment_anchor,
  "delete-review-comment": a_delete_review_comment,
  "update-review-comment": a_update_review_comment,
  "consume-review-feedback": a_consume_review_feedback,
  "get-review-feedback": a_get_review_feedback,
  "set-review-status": a_set_review_status,
  "send-review-thread-to-agent": a_send_review_thread_to_agent,
  "react-to-review-comment": a_react_to_review_comment,
  "set-review-thread-unread": a_set_review_thread_unread,
  "set-review-threads-unread": a_set_review_threads_unread,
  "set-review-thread-muted": a_set_review_thread_muted,
  "create-resource-suggestion": a_create_resource_suggestion,
  "create-resource-suggestion-proposal": a_create_resource_suggestion_proposal,
  "get-resource-suggestion-proposal-by-creation-key": a_get_resource_suggestion_proposal_by_creation_key,
  "decide-resource-suggestion-proposal": a_decide_resource_suggestion_proposal,
  "update-resource-suggestion": a_update_resource_suggestion,
  "list-resource-suggestions": a_list_resource_suggestions,
  "get-resource-suggestion": a_get_resource_suggestion,
  "decide-resource-suggestion": a_decide_resource_suggestion,
};

export default modules;
